export const styles = {
  editorLayout: {
    width: "100%",
    height: "100%",
  },
  wrapper: {
    padding: "1rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  controlsContainer: {
    display: "flex",
    alignItems: "center",
    marginTop: "1rem",
    marginBottom: "1rem",
  },
  wrapperClass: {
    padding: "1rem",
    border: "1px solid #000",
    backgroundColor: "#f7f7f7",
    width: "40%",
  },
  editorClass: {
    padding: "1rem",
    backgroundColor: "#f7f7f7",
    maxHeight: "300px",
    minHeight: "150px",
    resize: "none",
    border: "1px solid #000",
  },
  toolbarClass: {
    border: "1px solid #000",
    backgroundColor: "#f7f7f7",
  },
  cartaPreview: {
    backgroundColor: "white",
    border: "1px solid #000",
    width: "215.9mm",
    height: "279.4mm",
  },
  oficioPreview: {
    backgroundColor: "white",
    border: "1px solid #000",
    width: "210.0mm",
    height: "297.0mm",
  },
  livePreview: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "1rem",
    marginBottom: "1rem",
  },
  content: {
    fontSize: "var(--font-size, 12px)",
    width: "calc(100% - var(--margin-left, 5mm) - var(--margin-right, 5mm))",
    lineHeight: "var(--line-spacing, 5mm)",
    marginLeft: "var(--margin-left, 5mm)",
    marginRight: "var(--margin-right, 5mm)",
    marginTop: "var(--margin-top, 5mm)",
    marginBottom: "var(--margin-bottom, 5mm)",
    textAlign: "left",
    overflowWrap: "break-word",
    border: "1px solid #e5e5e5",
  },
  gridContainer: {
    margin: "10px",
    width: "40%",
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gridGap: "10px",
  },
  gridItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
};
